language: node_js
node_js:
  - '6.2.2'

before_install:
  - npm install -g bower gulp typings firebase-tools

script:
  - gulp build-dist

after_success:
  - ls -R
  - firebase deploy --token ${FIREBASE_TOKEN}

notifications:
  email:
    - jeevan@jeevanjames.com
  webhooks: https://outlook.office365.com/webhook/6fa8f3c6-c8df-4aee-9ba7-c9bac0e22f1c@c6c1e9da-5d0c-4f8f-9a02-3c67206efbd6/TravisCI/a0bd584055a341229fa183fab269fe23/4e57288a-dffc-43b3-a2e0-1fafb92720c5
